sudo: false
language: ruby
rvm:
  - jruby-9.1.15.0 # latest stable
  - 2.2.7
  - 2.3.4
  - 2.4.1
  - ruby-head
before_install: gem install bundler -v 1.16.0

env:
  global:
    - JRUBY_OPTS="--dev -J-Djruby.launch.inproc=true -J-Xmx1024M"

matrix:
  allow_failures:
    - rvm: ruby-head
  fast_finish: true
