sudo: false
language: ruby
rvm:
  - jruby-9.1.15.0 # latest stable
  - 2.2.7
  - 2.3.4
  - 2.4.1
  - 2.5.0
  - ruby-head

env:
  global:
    - JRUBY_OPTS="--dev -J-Djruby.launch.inproc=true -J-Xmx1024M"
    - COVERAGE=true

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-9.1.15.0
  fast_finish: true
